resolver: lts-5.10
ghc-build: nopie
packages:
  - open-union
  - type-fun
  - stitch
  - safe
extra-deps:
- haste-lib-0.6.0.0@sha256:ca8b099d7803ef19687b7f81a1960cb4370f7a454eb1c6b4b1e04cc847aeaa50
- haste-prim-0.6.0.0@sha256:d0b7cbd39678e89a55e357bc2c6b0235fe1a78a271d7795c71647bc342761f74

nix:
  enable: true
  path: ["nixpkgs=https://github.com/NixOS/nixpkgs/archive/16.09.tar.gz"]
  packages: ["zlib", "bzip2", "ncurses", "curl"]
  add-gc-roots: true
